wallpaper {
    monitor = DP-3
    path = ~/Wallpapers/animegirl.jpg
    fit_mode = cover
} 
wallpaper {
    monitor = HDMI-A-1
    path = ~/Wallpapers/animegirl.jpg
    fit_mode = cover 
}

splash = 0
